# Generated by Django 5.1.7 on 2025-05-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='foto_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='foto_produto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
