# Generated by Django 5.1.7 on 2025-05-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_produto_foto_produto_produto_foto_produto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto_produto_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
