# Generated by Django 5.1.7 on 2025-05-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_produto_foto_produto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria_produto',
            field=models.CharField(choices=[('LAN', 'Lanches'), ('PTP', 'Pratos Principais'), ('BEB', 'Bebidas'), ('SOB', 'Sobremesas'), ('COM', 'Combos')], default='LAN', max_length=3),
        ),
    ]
