# Generated by Django 5.1.7 on 2025-05-13 02:49

import django.core.validators
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_produto_categoria_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['categoria_produto', 'nome_produto'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria_produto',
            field=models.CharField(choices=[('LAN', 'Lanches'), ('PTP', 'Pratos Principais'), ('BEB', 'Bebidas'), ('SOB', 'Sobremesas'), ('COM', 'Combos')], default='LAN', max_length=3, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='desc_produto',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto_produto_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Foto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id_produto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_produto',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço'),
        ),
    ]
