# Generated by Django 5.1.7 on 2025-05-13 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_produto_options_produto_disponivel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome_produto'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
