# Generated by Django 5.1.7 on 2025-05-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_pedido_itempedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_produto_currency',
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_produto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço'),
        ),
    ]
